services:
  # ====================================
  # FoundryVTT
  # ====================================
  foundryvtt:
    image: felddy/foundryvtt:11
    container_name: foundryvtt
    init: true
    restart: unless-stopped
    ports:
      - 30000:30000/tcp
    volumes:
      - ./volumes/foundry-vtt/data:/data # FoundryVTT data
      - ./src:/data/Data/modules/pretty-mixer # THIS plugin
      - ./data:/data/Data/dev_assets # dev assets (music)
    env_file:
      - ./foundry.env
